In [1]:
import tensorflow as tf
from tensorflow.keras import backend as K

## Euclidean Distance

In [5]:
x, y = tf.constant([[1,2,3],[1,2,3]],dtype=tf.float32),tf.constant([[2,3,4],[1,2,3]],dtype=tf.float32)
square = tf.math.square(x - y)
print(square)


tf.Tensor(
[[1. 1. 1.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [6]:
sum_square = tf.math.reduce_sum(square, axis=1, keepdims=True)
print(sum_square)


tf.Tensor(
[[3.]
 [0.]], shape=(2, 1), dtype=float32)


In [7]:
result = tf.math.sqrt(tf.math.maximum(sum_square, K.epsilon()))  
print(result)

tf.Tensor(
[[1.7320508e+00]
 [3.1622776e-04]], shape=(2, 1), dtype=float32)


## Focal loss

In [ ]:

def focal_loss(y_true, y_pred, gamma = 2.0, alpha = 0.8):
    #https://zhuanlan.zhihu.com/p/103623160
    pt_1 = tf.where(tf.equal(y_true, 1), y_pred, tf.ones_like(y_pred))
    pt_0 = tf.where(tf.equal(y_true, 0), y_pred, tf.zeros_like(y_pred))
    return - K.sum(alpha * K.pow(1. - pt_1, gamma) * K.log(pt_1)) - K.sum((1-alpha) * K.pow( pt_0, gamma) * K.log(1. - pt_0))

In [ ]:
#https://zhuanlan.zhihu.com/p/103623160
def focal_loss(gamma = 2.0, alpha = 0.8):   
    def focal_loss_fixed(y_true, y_pred):
        pt_1 = tf.where(tf.equal(y_true, 1), y_pred, tf.ones_like(y_pred))
        pt_0 = tf.where(tf.equal(y_true, 0), y_pred, tf.zeros_like(y_pred))
        return - K.sum(alpha * K.pow(1. - pt_1, gamma) * K.log(pt_1)) - K.sum((1-alpha) * K.pow( pt_0, gamma) * K.log(1. - pt_0))
    return focal_loss_fixed